# Generated by Django 2.0.2 on 2020-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTest_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=164)),
                ('test_response', models.CharField(max_length=2048)),
                ('test_result', models.CharField(max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
                ('tester', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
            },
        ),
        migrations.CreateModel(
            name='IpUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '登录用户ip获取',
                'verbose_name_plural': '登录用户ip获取',
            },
        ),
        migrations.CreateModel(
            name='Report_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=164)),
                ('reporter_type', models.CharField(choices=[('All', '全量用例'), ('Nec', '必测用例'), ('Single', '单条用例')], default='全量用例', max_length=32)),
                ('create_user', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('report_style', models.CharField(choices=[('1', '批量执行'), ('2', '单条执行')], default='1', max_length=8)),
                ('env_Id', models.CharField(default='4', max_length=8)),
                ('report_testAll', models.IntegerField(default=0)),
                ('report_testPass', models.IntegerField(default=0)),
                ('report_testFail', models.IntegerField(default=0)),
                ('report_testError', models.IntegerField(default=0)),
                ('report_successRate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('post', 'POST'), ('get', 'GET')], default='GET', max_length=64)),
                ('header', models.CharField(max_length=256)),
                ('params', models.CharField(max_length=1024)),
                ('apiname', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=1024)),
                ('result', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': '接口请求',
                'verbose_name_plural': '接口请求',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SendCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_type', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('exchangeType', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name_ch', models.CharField(max_length=64)),
                ('case_name_en', models.CharField(max_length=64)),
                ('case_steps', models.CharField(max_length=128)),
                ('script_name', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('case_creater', models.CharField(default='lazy', max_length=64)),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('1', '管理员'), ('2', '普通用户')], default='2', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
