# Generated by Django 2.0.2 on 2019-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('post', 'POST'), ('get', 'GET')], default='GET', max_length=64)),
                ('header', models.CharField(max_length=256)),
                ('params', models.CharField(max_length=1024)),
                ('apiname', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=1024)),
            ],
        ),
    ]
