# Generated by Django 3.0.8 on 2020-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=16)),
                ('test_response', models.CharField(max_length=16)),
                ('test_result', models.CharField(max_length=16)),
                ('test_time', models.DateTimeField()),
                ('test', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '测试表',
            },
        ),
    ]
