# Generated by Django 3.0.8 on 2020-08-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
