# Generated by Django 2.0.2 on 2020-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_location', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'app_event_info',
            },
        ),
    ]
