# Generated by Django 2.0.2 on 2019-12-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_api'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='Requests',
        ),
    ]
