# Generated by Django 2.0.2 on 2020-07-23 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_sendcode_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_results',
            name='publish_module',
            field=models.CharField(default='yyting-apps-api', max_length=64),
        ),
        migrations.AlterField(
            model_name='sendcode',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
