# Generated by Django 2.0.2 on 2019-12-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191224_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['id'], 'verbose_name': '请求', 'verbose_name_plural': '请求'},
        ),
        migrations.AddField(
            model_name='requests',
            name='result',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
    ]
