# Generated by Django 2.0.2 on 2019-12-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191224_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_type', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('exchangeType', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
            },
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['id'], 'verbose_name': '接口请求', 'verbose_name_plural': '接口请求'},
        ),
    ]
