# Generated by Django 3.0.8 on 2020-08-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_settlement_vip_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement_not_vip_models',
            name='baseBillingAounmt_subtract_techAmount_Original',
        ),
        migrations.RemoveField(
            model_name='settlement_not_vip_models',
            name='base_billing_amount_original',
        ),
        migrations.RemoveField(
            model_name='settlement_not_vip_models',
            name='partner_amount_original',
        ),
        migrations.RemoveField(
            model_name='settlement_not_vip_models',
            name='sum_commission_in_original',
        ),
        migrations.RemoveField(
            model_name='settlement_not_vip_models',
            name='tech_amount_original',
        ),
    ]
