# Generated by Django 2.0.2 on 2020-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_sendcode_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '登录用户ip获取',
                'verbose_name_plural': '登录用户ip获取',
            },
        ),
    ]
