# Generated by Django 3.0.8 on 2020-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200807_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement_not_vip_models',
            name='business',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AddField(
            model_name='settlement_not_vip_models',
            name='entity_id',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AddField(
            model_name='settlement_not_vip_models',
            name='partner_id',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AddField(
            model_name='settlement_not_vip_models',
            name='settlement_month',
            field=models.CharField(default='Null', max_length=32),
        ),
    ]
