# Generated by Django 2.0.2 on 2020-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_iputils'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name_ch', models.CharField(max_length=64)),
                ('case_name_en', models.CharField(max_length=64)),
                ('case_steps', models.CharField(max_length=128)),
                ('script_name', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
