# Generated by Django 3.0.8 on 2020-08-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200807_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement_vip_models',
            name='entity_id',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AddField(
            model_name='settlement_vip_models',
            name='partner_id',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AddField(
            model_name='settlement_vip_models',
            name='settlement_month',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='baseBillingAounmt_subtract_techAmount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='base_billing_amount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='channel_partner_amount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='partner_amount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='sum_cash_flow',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='sum_cash_flow_billing',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='sum_commission_in',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_not_vip_models',
            name='tech_amount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_vip_models',
            name='book_playCount',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_vip_models',
            name='partner_divide_money_final',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_vip_models',
            name='partner_divide_rate',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_vip_models',
            name='sum_cash_flow',
            field=models.CharField(default='Null', max_length=64),
        ),
        migrations.AlterField(
            model_name='settlement_vip_models',
            name='tech_service_consumption',
            field=models.CharField(default='Null', max_length=64),
        ),
    ]
