# Generated by Django 3.0.8 on 2020-08-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200815_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='settlement_channel_vip_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_month', models.CharField(default='Null', max_length=32)),
                ('partner_id', models.CharField(default='Null', max_length=32)),
                ('can_divide_amount', models.CharField(max_length=64)),
                ('divide_baseAmount_final', models.CharField(max_length=64)),
                ('pay_amount', models.CharField(max_length=64)),
                ('channel_lr_amount', models.CharField(max_length=64)),
                ('settlement_amount', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '渠道VIP会员业务结算结果',
            },
        ),
        migrations.AlterModelOptions(
            name='settlement_vip_models',
            options={'verbose_name': '版权/主播VIP会员业务结算结果'},
        ),
    ]
