# Generated by Django 2.0.2 on 2020-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_report_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', '管理员'), ('2', '普通用户')], default='普通用户', max_length=32),
        ),
    ]
