# Generated by Django 2.0.2 on 2020-04-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200417_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', '管理员'), ('2', '普通用户')], default='2', max_length=32),
        ),
    ]
