# Generated by Django 2.0.2 on 2020-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200417_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTest_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=164)),
                ('test_response', models.CharField(max_length=2048)),
                ('test_result', models.CharField(max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
                ('tester', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
            },
        ),
        migrations.AddField(
            model_name='report_results',
            name='report_style',
            field=models.CharField(choices=[('1', '批量执行'), ('2', '单条执行')], default='批量执行', max_length=8),
        ),
    ]
