# Generated by Django 2.0.2 on 2020-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200424_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_results',
            name='report_style',
            field=models.CharField(choices=[('1', '批量执行'), ('2', '单条执行')], default='1', max_length=8),
        ),
    ]
