# Generated by Django 2.0.2 on 2020-04-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200424_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_results',
            name='reporter_type',
            field=models.CharField(choices=[('All', '全量用例'), ('Nec', '必测用例'), ('Single', '单条用例')], default='全量用例', max_length=32),
        ),
    ]
