# Generated by Django 2.0.2 on 2020-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_report_results_env_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='case_creater',
            field=models.CharField(default='lazy', max_length=64),
        ),
    ]
